# -*- coding: utf-8 -*-
"""AI_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_H3M_70YoWIGCPzxovZOIZTQ6bPuc87D
"""

!pip install torch transformers matplotlib --quiet

import math
import random
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from transformers import AutoTokenizer, AutoModel

import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
device

class RegimeController(nn.Module):
    """
    Predicts regime z_t from:
    - previous hidden state h_{t-1}
    - current message embedding x_t
    """
    def __init__(self, state_dim: int, input_dim: int, num_regimes: int):
        super().__init__()
        self.num_regimes = num_regimes
        self.net = nn.Sequential(
            nn.Linear(state_dim + input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, num_regimes)
        )

    def forward(self, h_prev: torch.Tensor, x_t: torch.Tensor):
        """
        h_prev: (batch, state_dim)
        x_t: (batch, input_dim)
        returns:
            logits: (batch, num_regimes)
        """
        inp = torch.cat([h_prev, x_t], dim=-1)
        logits = self.net(inp)
        return logits

class NeuralSSM(nn.Module):
    """
    Neural state-space model:
        h_t = f(h_{t-1}, x_t, one_hot(z_t))
    """
    def __init__(self, state_dim: int, input_dim: int, num_regimes: int):
        super().__init__()
        self.state_dim = state_dim
        self.input_dim = input_dim
        self.num_regimes = num_regimes

        self.update_net = nn.Sequential(
            nn.Linear(state_dim + input_dim + num_regimes, 256),
            nn.Tanh(),
            nn.Linear(256, state_dim)
        )

    def forward(self, h_prev: torch.Tensor, x_t: torch.Tensor, z_t: torch.Tensor):
        """
        h_prev: (batch, state_dim)
        x_t: (batch, input_dim)
        z_t: (batch,) long regime indices
        """
        batch_size = h_prev.size(0)
        z_onehot = torch.zeros(batch_size, self.num_regimes, device=h_prev.device)
        z_onehot.scatter_(1, z_t.unsqueeze(1), 1.0)

        inp = torch.cat([h_prev, x_t, z_onehot], dim=-1)
        h_t = self.update_net(inp)
        return h_t

# Small sentence encoder backbone
ENCODER_NAME = "distilbert-base-uncased"

enc_tokenizer = AutoTokenizer.from_pretrained(ENCODER_NAME)
enc_model = AutoModel.from_pretrained(ENCODER_NAME).to(device)
enc_model.eval()

embed_dim = enc_model.config.hidden_size
embed_dim

@torch.no_grad()
def encode_text_batch(text_list):
    """
    text_list: list of strings
    returns: (batch, embed_dim) embeddings
    """
    enc = enc_tokenizer(
        text_list,
        return_tensors="pt",
        truncation=True,
        padding=True
    ).to(device)

    outputs = enc_model(**enc)
    # Mean-pool over tokens
    pooled = outputs.last_hidden_state.mean(dim=1)  # (batch, hidden)
    return pooled

REGIME_NAMES = ["EXPLAINER", "TUTOR", "CONCISE"]
NUM_REGIMES = len(REGIME_NAMES)
SEQ_LEN = 5

def generate_message(step, conv_id):
    # Just to have some variation in text
    templates = [
        "Conversation {c}, step {s}: please help me understand neural networks.",
        "In convo {c}, at turn {s}, I still don't get backpropagation.",
        "Convo {c} / turn {s}: can you clarify this concept?",
        "We are at step {s} of conversation {c}. Explain more about AI.",
        "Convo {c}, step {s}: now I just want a short recap."
    ]
    t = random.choice(templates)
    return t.format(c=conv_id, s=step)

def true_regime(step):
    if step == 0:
        return 0  # EXPLAINER
    elif step in [1, 2]:
        return 1  # TUTOR
    else:
        return 2  # CONCISE

@dataclass
class ConvExample:
    messages: list  # list of strings length SEQ_LEN
    regimes: list   # list of ints length SEQ_LEN

def generate_dataset(num_convs=800):
    data = []
    for cid in range(num_convs):
        msgs = []
        regs = []
        for t in range(SEQ_LEN):
            msgs.append(generate_message(step=t, conv_id=cid))
            regs.append(true_regime(t))
        data.append(ConvExample(messages=msgs, regimes=regs))
    return data

full_data = generate_dataset(num_convs=800)
len(full_data), full_data[0]

random.seed(42)
torch.manual_seed(42)

random.shuffle(full_data)
split = int(0.8 * len(full_data))
train_data = full_data[:split]
test_data  = full_data[split:]

def embed_conversations(data):
    """
    data: list[ConvExample]
    returns:
        msg_embs: (num_convs, SEQ_LEN, embed_dim)
        regimes: (num_convs, SEQ_LEN)
    """
    all_texts = []
    idx_map = []  # (conv_index, step)
    for ci, conv in enumerate(data):
        for t, msg in enumerate(conv.messages):
            all_texts.append(msg)
            idx_map.append((ci, t))

    embs = []
    BATCH = 32
    for i in range(0, len(all_texts), BATCH):
        batch_texts = all_texts[i:i+BATCH]
        emb_batch = encode_text_batch(batch_texts)
        embs.append(emb_batch.cpu())
    embs = torch.cat(embs, dim=0)  # (total_msgs, embed_dim)

    num_convs = len(data)
    msg_embs = torch.zeros(num_convs, SEQ_LEN, embed_dim)
    regimes = torch.zeros(num_convs, SEQ_LEN, dtype=torch.long)

    for idx, (ci, t) in enumerate(idx_map):
        msg_embs[ci, t] = embs[idx]
        regimes[ci, t] = data[ci].regimes[t]

    return msg_embs, regimes

train_embs, train_regimes = embed_conversations(train_data)
test_embs,  test_regimes  = embed_conversations(test_data)

train_embs.shape, train_regimes.shape, test_embs.shape

class BaselineRegimeClassifier(nn.Module):
    def __init__(self, input_dim: int, num_regimes: int):
        super().__init__()
        self.linear = nn.Linear(input_dim, num_regimes)

    def forward(self, x):
        # x: (batch, embed_dim)
        return self.linear(x)

def train_baseline(
    train_embs, train_regimes,
    test_embs, test_regimes,
    num_epochs=15,
    lr=1e-3
):
    model = BaselineRegimeClassifier(embed_dim, NUM_REGIMES).to(device)
    opt = optim.Adam(model.parameters(), lr=lr)
    crit = nn.CrossEntropyLoss()

    history = {"train_loss": [], "test_acc": []}

    for epoch in range(num_epochs):
        model.train()
        # Flatten sequences into (N*T, dim)
        x_train = train_embs.view(-1, embed_dim).to(device)
        y_train = train_regimes.view(-1).to(device)

        opt.zero_grad()
        logits = model(x_train)
        loss = crit(logits, y_train)
        loss.backward()
        opt.step()

        # Eval
        model.eval()
        with torch.no_grad():
            x_test = test_embs.view(-1, embed_dim).to(device)
            y_test = test_regimes.view(-1).to(device)
            logits_test = model(x_test)
            preds = logits_test.argmax(dim=-1)
            acc = (preds == y_test).float().mean().item()

        history["train_loss"].append(loss.item())
        history["test_acc"].append(acc)

        print(f"[Baseline] Epoch {epoch+1}/{num_epochs} - "
              f"loss={loss.item():.4f} - test_acc={acc*100:.2f}%")

    return model, history

baseline_model, baseline_hist = train_baseline(
    train_embs, train_regimes,
    test_embs, test_regimes,
    num_epochs=15
)

class SSMRegimeModel(nn.Module):
    def __init__(self, input_dim, state_dim, num_regimes):
        super().__init__()
        self.state_dim = state_dim
        self.num_regimes = num_regimes

        self.ssm = NeuralSSM(state_dim=state_dim, input_dim=input_dim, num_regimes=num_regimes)
        self.controller = RegimeController(state_dim=state_dim, input_dim=input_dim, num_regimes=num_regimes)

        self.h0 = nn.Parameter(torch.zeros(state_dim))

    def forward(self, seq_embs, seq_regimes=None):
        """
        seq_embs: (batch, T, input_dim)
        seq_regimes: (batch, T) or None
        returns:
            logits_seq: (batch, T, num_regimes)
        """
        batch_size, T, D = seq_embs.shape
        device = seq_embs.device

        h = self.h0.unsqueeze(0).expand(batch_size, -1)  # (batch, state_dim)
        logits_list = []

        for t in range(T):
            x_t = seq_embs[:, t, :]  # (batch, D)

            # Predict regime from (h_{t-1}, x_t)
            logits_t = self.controller(h, x_t)  # (batch, num_regimes)
            logits_list.append(logits_t.unsqueeze(1))

            if seq_regimes is None:
                # During inference we could sample / argmax, but for training we use teacher forcing
                z_t = logits_t.argmax(dim=-1)
            else:
                z_t = seq_regimes[:, t]

            # Update state
            h = self.ssm(h, x_t, z_t)

        logits_seq = torch.cat(logits_list, dim=1)  # (batch, T, num_regimes)
        return logits_seq

def train_ssm_model(
    train_embs, train_regimes,
    test_embs, test_regimes,
    state_dim=64,
    num_epochs=15,
    lr=1e-3
):
    model = SSMRegimeModel(
        input_dim=embed_dim,
        state_dim=state_dim,
        num_regimes=NUM_REGIMES
    ).to(device)

    opt = optim.Adam(model.parameters(), lr=lr)
    crit = nn.CrossEntropyLoss()

    history = {"train_loss": [], "test_acc": []}

    for epoch in range(num_epochs):
        model.train()
        x_train = train_embs.to(device)      # (N, T, D)
        y_train = train_regimes.to(device)   # (N, T)

        opt.zero_grad()
        logits_seq = model(x_train, seq_regimes=y_train)  # (N, T, K)
        loss = crit(
            logits_seq.view(-1, NUM_REGIMES),
            y_train.view(-1)
        )
        loss.backward()
        opt.step()

        # Eval
        model.eval()
        with torch.no_grad():
            x_test = test_embs.to(device)
            y_test = test_regimes.to(device)
            logits_test_seq = model(x_test, seq_regimes=y_test)
            preds = logits_test_seq.argmax(dim=-1)
            acc = (preds == y_test).float().mean().item()

        history["train_loss"].append(loss.item())
        history["test_acc"].append(acc)

        print(f"[SSM] Epoch {epoch+1}/{num_epochs} - "
              f"loss={loss.item():.4f} - test_acc={acc*100:.2f}%")

    return model, history

ssm_model, ssm_hist = train_ssm_model(
    train_embs, train_regimes,
    test_embs, test_regimes,
    state_dim=64,
    num_epochs=15
)

epochs = list(range(1, len(baseline_hist["test_acc"]) + 1))

plt.figure()
plt.plot(epochs, [a * 100 for a in baseline_hist["test_acc"]], label="Baseline (no SSM)")
plt.plot(epochs, [a * 100 for a in ssm_hist["test_acc"]], label="SSM regime model")
plt.xlabel("Epoch")
plt.ylabel("Test Accuracy (%)")
plt.title("Regime prediction accuracy vs. epoch")
plt.legend()
plt.grid(True)
plt.show()

print("Final baseline test accuracy: {:.2f}%".format(baseline_hist["test_acc"][-1] * 100))
print("Final SSM test accuracy:      {:.2f}%".format(ssm_hist["test_acc"][-1] * 100))

# from transformers import AutoModelForCausalLM

# LLM_NAME = "gpt2"

# gen_tokenizer = AutoTokenizer.from_pretrained(LLM_NAME)
# if gen_tokenizer.pad_token is None:
#     gen_tokenizer.pad_token = gen_tokenizer.eos_token

# gen_model = AutoModelForCausalLM.from_pretrained(LLM_NAME).to(device)
# gen_model.eval()

from transformers import AutoModelForCausalLM, AutoTokenizer

# You can change this to another instruct/chat model if needed
LLM_NAME = "mistralai/Mistral-7B-Instruct-v0.1"
# examples of other options (commented):
# LLM_NAME = "tiiuae/falcon-7b-instruct"
# LLM_NAME = "microsoft/phi-3-mini-4k-instruct"   # if available in your env

gen_tokenizer = AutoTokenizer.from_pretrained(LLM_NAME)

gen_model = AutoModelForCausalLM.from_pretrained(
    LLM_NAME,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
)
gen_model.to(device)
gen_model.eval()

print("Loaded chat LLM:", LLM_NAME, "on", device)

# def format_prompt(history, user_message, regime_idx):
#     tag = REGIME_NAMES[regime_idx]  # EXPLAINER / TUTOR / CONCISE

#     history_text = ""
#     for role, msg in history:
#         history_text += f"{role.upper()}: {msg}\n"

#     prompt = (
#         f"[MODE: {tag}]\n"
#         f"{history_text}"
#         f"USER: {user_message}\n"
#         f"ASSISTANT:"
#     )
#     return prompt

def build_chat_messages(history, user_message, regime_idx):
    """
    history: list[(role, text)] where role is "user" or "assistant"
    user_message: current user text
    regime_idx: int, index into REGIME_NAMES
    """
    mode = REGIME_NAMES[regime_idx]  # EXPLAINER / TUTOR / CONCISE

    system_content = {
        "EXPLAINER": (
            "You are a helpful AI assistant. "
            "Current mode: EXPLAINER. Give detailed multi-sentence explanations."
        ),
        "TUTOR": (
            "You are a patient step-by-step tutor. "
            "Current mode: TUTOR. Answer in numbered steps with clear reasoning."
        ),
        "CONCISE": (
            "You are a concise assistant. "
            "Current mode: CONCISE. Answer in one or two short sentences only."
        )
    }[mode]

    messages = [
        {"role": "system", "content": system_content}
    ]

    for role, text in history:
        if role == "user":
            messages.append({"role": "user", "content": text})
        else:
            messages.append({"role": "assistant", "content": text})

    # current user turn
    messages.append({"role": "user", "content": user_message})
    return messages


def generate_chat_response(history, user_message, regime_idx, max_new_tokens=128, temperature=0.7):
    """
    Use the advanced chat LLM with its chat template.
    """
    messages = build_chat_messages(history, user_message, regime_idx)

    input_ids = gen_tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True   # tells model it's assistant's turn
    ).to(device)

    with torch.no_grad():
        output_ids = gen_model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            pad_token_id=gen_tokenizer.eos_token_id,
        )

    # Decode only the newly generated tokens (after the prompt)
    gen_tokens = output_ids[0, input_ids.shape[-1]:]
    response = gen_tokenizer.decode(gen_tokens, skip_special_tokens=True).strip()
    return response

ssm_model.eval()

def predict_regime_for_turn(ssm_model, prev_h, x_t):
    """
    prev_h: (1, state_dim) or None
    x_t: (1, embed_dim)
    returns: regime_idx (int), new_h (1, state_dim)
    """
    with torch.no_grad():
        if prev_h is None:
            h = ssm_model.h0.unsqueeze(0).to(device)
        else:
            h = prev_h

        logits = ssm_model.controller(h, x_t)   # (1, num_regimes)
        regime_idx = logits.argmax(dim=-1)      # (1,)
        z_t = regime_idx                        # teacher forcing at inference is fine here

        new_h = ssm_model.ssm(h, x_t, z_t)      # (1, state_dim)

    return regime_idx.item(), new_h


def hybrid_chat():
    history = []
    h_state = None

    print("Hybrid SSM +", LLM_NAME, "chatbot. Type 'quit' to stop.\n")

    while True:
        user_msg = input("You: ")
        if user_msg.strip().lower() in ["quit", "exit", "q"]:
            break

        # 1) embed user message using the frozen encoder
        x_t = encode_text_batch([user_msg]).to(device)   # (1, embed_dim)

        # 2) predict regime using trained SSM model
        regime_idx, h_state = predict_regime_for_turn(ssm_model, h_state, x_t)

        # 3) generate assistant response with the chat LLM
        response = generate_chat_response(
            history=history,
            user_message=user_msg,
            regime_idx=regime_idx,
            max_new_tokens=128,
            temperature=0.7,
        )

        history.append(("user", user_msg))
        history.append(("assistant", response))

        print(f"[Regime = {regime_idx} -> {REGIME_NAMES[regime_idx]}]")
        print("Assistant:", response)
        print("-" * 60)

hybrid_chat()

# baseline chatbot
# ---------- Baseline chatbot (no SSM) ----------

BASELINE_SYSTEM_PROMPT = (
    "You are a helpful general-purpose AI assistant. "
    "Answer the user's questions clearly and politely."
)

def baseline_build_messages(history, user_message):
    """
    history: list of (role, text) for previous turns
    user_message: current user input
    """
    messages = [{"role": "system", "content": BASELINE_SYSTEM_PROMPT}]
    for role, text in history:
        if role == "user":
            messages.append({"role": "user", "content": text})
        else:
            messages.append({"role": "assistant", "content": text})
    messages.append({"role": "user", "content": user_message})
    return messages


def baseline_generate_response(history, user_message,
                               max_new_tokens=128, temperature=0.7):
    """
    Use the same advanced chat LLM, but with a single fixed system prompt.
    No regimes, no SSM.
    """
    messages = baseline_build_messages(history, user_message)

    input_ids = gen_tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    ).to(device)

    with torch.no_grad():
        output_ids = gen_model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            pad_token_id=gen_tokenizer.eos_token_id,
        )

    gen_tokens = output_ids[0, input_ids.shape[-1]:]
    response = gen_tokenizer.decode(gen_tokens, skip_special_tokens=True).strip()
    return response

# ---------- Hybrid chatbot (SSM regimes + chat LLM) ----------

def build_chat_messages(history, user_message, regime_idx):
    mode = REGIME_NAMES[regime_idx]  # EXPLAINER / TUTOR / CONCISE

    system_content = {
        "EXPLAINER": (
            "You are a helpful AI assistant. "
            "Current mode: EXPLAINER. Give detailed multi-sentence explanations."
        ),
        "TUTOR": (
            "You are a patient step-by-step tutor. "
            "Current mode: TUTOR. Answer in numbered steps with clear reasoning."
        ),
        "CONCISE": (
            "You are a concise assistant. "
            "Current mode: CONCISE. Answer in one or two short sentences only."
        )
    }[mode]

    messages = [{"role": "system", "content": system_content}]
    for role, text in history:
        if role == "user":
            messages.append({"role": "user", "content": text})
        else:
            messages.append({"role": "assistant", "content": text})
    messages.append({"role": "user", "content": user_message})
    return messages


def generate_chat_response(history, user_message, regime_idx,
                           max_new_tokens=128, temperature=0.7):
    messages = build_chat_messages(history, user_message, regime_idx)

    input_ids = gen_tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    ).to(device)

    with torch.no_grad():
        output_ids = gen_model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            pad_token_id=gen_tokenizer.eos_token_id,
        )

    gen_tokens = output_ids[0, input_ids.shape[-1]:]
    response = gen_tokenizer.decode(gen_tokens, skip_special_tokens=True).strip()
    return response


ssm_model.eval()

def predict_regime_for_turn(ssm_model, prev_h, x_t):
    """
    prev_h: (1, state_dim) or None
    x_t: (1, embed_dim)
    returns: regime_idx (int), new_h (1, state_dim)
    """
    with torch.no_grad():
        if prev_h is None:
            h = ssm_model.h0.unsqueeze(0).to(device)
        else:
            h = prev_h

        logits = ssm_model.controller(h, x_t)
        regime_idx = logits.argmax(dim=-1)  # (1,)
        z_t = regime_idx
        new_h = ssm_model.ssm(h, x_t, z_t)

    return regime_idx.item(), new_h

# ---------- Scripted comparison run ----------

scripted_prompts = [
    "What is ChatGPT? Explain it in detail.",
    "Can you walk me through step by step how it works internally?",
    "I'm still confused. Can you tutor me through a simple example?",
    "Now give me a one-sentence summary I can tell my friend."
]

def run_comparison(prompts, max_new_tokens=160):
    # Baseline conversation state
    base_history = []

    # Hybrid conversation state
    hyb_history = []
    h_state = None

    print("=== Baseline vs Hybrid (SSM) Comparison ===\n")

    for turn_idx, user_msg in enumerate(prompts):
        print(f"------------- TURN {turn_idx} -------------")
        print("User:", user_msg, "\n")

        # -------- Baseline chatbot --------
        base_resp = baseline_generate_response(
            history=base_history,
            user_message=user_msg,
            max_new_tokens=max_new_tokens,
            temperature=0.7
        )
        base_history.append(("user", user_msg))
        base_history.append(("assistant", base_resp))

        print("[Baseline chatbot response]")
        print(base_resp, "\n")

        # -------- Hybrid SSM chatbot --------
        # 1) embed user message
        x_t = encode_text_batch([user_msg]).to(device)   # (1, embed_dim)

        # 2) predict regime using SSM
        regime_idx, h_state = predict_regime_for_turn(ssm_model, h_state, x_t)
        regime_name = REGIME_NAMES[regime_idx]

        # 3) generate response with regime-conditioned system prompt
        hyb_resp = generate_chat_response(
            history=hyb_history,
            user_message=user_msg,
            regime_idx=regime_idx,
            max_new_tokens=max_new_tokens,
            temperature=0.7
        )
        hyb_history.append(("user", user_msg))
        hyb_history.append(("assistant", hyb_resp))

        print(f"[Hybrid chatbot response] (Regime = {regime_idx} -> {regime_name})")
        print(hyb_resp)
        print("\n" + "=" * 60 + "\n")

# Run it:
run_comparison(scripted_prompts)

